version: 2

models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - unique:
              tags: ['dq:accuracy']
          - not_null:
              tags: ['dq:completeness']

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique:         
              tags: ['dq:accuracy']
          - not_null:
              tags: ['dq:completeness']
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
              tags: ['dq:consistency']
              

  - name: stg_payments
    columns:
      - name: payment_id
        tests:
          - unique:
              tags: ['dq:accuracy']
          - not_null:
              tags: ['dq:completeness']
      - name: payment_method
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']
              tags: ['dq:consistency']