version: 2

sources:
  - name: raw
    schema: "{{ 'raw_prod' if target.schema == 'data_prod' else 'raw_nonprod' }}"  # this dynamic setting is helpful for deployments
    #schema: raw_nonprod  # this manual setting is helpful for development (developing against nonprod data)
    #schema: raw_prod  # this manual setting is helpful for development (developing against prod data)
    description: This is a replica of the Postgres database used by our app
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}
    loaded_at_field: ingest_timestamp_utc

    tables:
      - name: raw_customers
        columns:
          - name: last_name
            tests:
              - my_generic_test

      - name: raw_orders
      - name: raw_payments